import React from 'react';
import Reflux from 'reflux';
import './Terms.css';

import TranslationStore from '../../stores/translationStore';

class Terms extends Reflux.Component {
  constructor(props) {
    super(props);
    this.store = TranslationStore;
  }

  render() {
    return (
      <section className="flex-col terms-page-container">
        <h2>Personal Data (Privacy) Policy Statement (“Privacy Statement”)</h2>
        <p>Hjobs Hong Kong pledges to meet fully with the requirements of the Personal Data (Privacy) Ordinance, Chapter 486 of the Laws of Hong Kong. In doing so, Hjobs Hong Kong will ensure compliance by its staff to the strictest standards of security and confidentiality in respect of all personal information and data submitted by users via the Site and Hjobs Hong Kong will not, subject to the terms herein, release such information to anyone without the prior consent of the relevant user(s) of the Site (whether registered or not) (“User(s)”). </p>
        <p>Users are strongly recommended to read this Privacy Statement carefully to have an understanding of Hjobs Hong Kong’s policy and practices with regard to the treatment of personal information and data provided by the Users on the Site. This Privacy Statement is applicable to both registered and unregistered Users, and the terms herein may be updated, revised, varied and/or amended from time to time as Hjobs Hong Kong may deem necessary and/or appropriate.</p>
        <p>By registering for or using the services/Site, or by clicking the ‘Sign up’ button, User:</p>
        <ul>
          <li>consent to Hjobs Hong Kong and/or Hjobs group companies collecting, using, disclosing and/or processing User’s personal data for the purposes as described below;</li>
          <li>consent to Hjobs Hong Kong and/or Hjobs group companies disclosing Users’ personal data to Hjobs Hong Kong’s and/or Hjobs group companies’ third party service providers or agents (whether within or outside Hong Kong) for the purposes as described below.</li>
        </ul>
        <p>If Users have questions or concerns regarding this Privacy Statement, they should contact the Customer Support representative of Hjobs Hong Kong’s Customer Service Department, whose contact details are set out under the section headed “Enquiries” below.</p>
        <p>In this Privacy Statement, the following terms shall have the respective meanings specified below unless the context otherwise requires:</p>
        <ul>
          <li><b>“Advertiser(s)”</b>: means user who places a job advertisement or promotes any job related activities via the Site.</li>
          <li><b>“Hjobs”</b>: means Hjobs Inc.</li>
          <li><b>“Hjobs Group”</b>: means Hjobs Hong Kong, Hjobs Singapore, Hjobs Thailand.</li>
          <li><b>“Hjobs Hong Kong”</b>: means Hjobs Hong Kong Limited.</li>
          <li><b>“Job Seeker(s)”</b>: means users seeking employment.</li>
          <li><b>“Sign up User(s)”</b>: means Users who sign up on the Site to obtain services offered by Hjobs. Unless the context provides otherwise, references in this Privacy Statement to “users” or “you” include references to generic users and Registered Users.</li>
          <li><b>“Site”</b>: means any website, job portal or mobile application owned and operated by Hjobs and its affiliates/subsidiaries or its service providers.</li>
        </ul>
        <h2>Purpose of Collection and Use of Personal Data</h2>
        <p>In the course of using the Site, Users may disclose or be asked to provide personal information and/or data. In order to have the benefit of and enjoy various services offered by the Site, it may be necessary for Users to provide Hjobs Hong Kong with their personal information and/or data. Although Users are not obliged to provide the information and/or data as requested on the Site, Hjobs Hong Kong will not be able to render certain services on the Site in the event that Users fail to do so.</p>
        <p>Hjobs Hong Kong’s purposes for collecting and using the information and data on the Site include but are not limited to the following:</p>
        <ul>
          <li>for the daily operation of the services provided to Users;</li>
          <li>to assist Job Seekers to find appropriate employment with Employers and to assist Employers to assess the suitability of candidates for job vacancy for a wide spectrum of jobs within the hospitality and/ or tourism industries;</li>
          <li>to provide Users with various services offered by the Site and newsletters, job openings and promotional and marketing materials (for further details, please refer to section headed “Subscription of Newsletter/Promotional Materials/Marketing Materials” below);</li>
          <li>to handle and follow up on enquiries, requests and complaints from Users;</li>
          <li>to contact Users regarding administrative notices and communications relevant to his/her use of the Site and to respond to Users’ inquiry or request;</li>
          <li>to assist Hjobs Hong Kong with developments for future marketing and promoting purposes or other internal purposes;</li>
          <li>to verify the identity of Users who have posted advertisements, materials, representations, messages, views or comments or such other information (collectively “Information”) on the Site;</li>
          <li>to identify Users who have viewed the Information posted on the Site;</li>
          <li>to allow Users to enjoy their benefits as members of the Site by enrolling for special events and promotions hosted by Hjobs Hong Kong and or its affiliates and or partner company;</li>
          <li>to identify Users who have enjoyed their benefits as members of the Site by receiving and using marketing promotional materials;</li>
          <li>to facilitate Hjobs Hong Kong and/or its affiliates to use the Users’ personal data for the purposes relating to the provision of services offered by Hjobs Hong Kong and marketing services and/or special event of Hjobs Hong Kong and/or its affiliates;</li>
          <li>to obtain statistics about Users to analyze usage of the Site in order to help its further development for internal use; and</li>
          <li>for purposes other than the above mentioned which are related to Hjobs Hong Kong’s and/or its affiliates’ provision of their product and/or services as Hjobs Hong Kong may deem fit.</li>
        </ul>
        <p>If a User is under the age of 16, Hjobs Hong Kong would strongly recommend him/her to seek prior consent from a person with parental responsibility for him/her, e.g. parent or guardian, who may contact the responsible Customer Support Executive whose contact details are set out under the section headed “Enquiries” for registering the User as member of the Site.</p>
        <p>Hjobs Hong Kong strives to only collect personal data which are necessary and adequate but not excessive in relation to the purposes set out hereinabove.</p>
        <p>If Hjobs Hong Kong requires the use of your personal data for a purpose other than those set out hereinabove, we will request your prescribed consent to the same. If you are a minor, the prescribed consent should be given by your parent or guardian.</p>
        <h3>Collection of Personal Data</h3>
        <p>Hjobs Hong Kong may collect personal information and/or data about a User such as his/her name, login ID and password, address, email address, phone number, age, gender, date of birth, country of residence, nationality, education level, certificate received and work experience that is/are not otherwise publicly available. Occasionally, Hjobs Hong Kong may also collect additional personal information and/or data from a User in connection with contests, surveys, or special offers.</p>
        <p>Only duly authorized staff of Hjobs Hong Kong will be permitted to access Users’ personal information and data, and Hjobs Hong Kong shall not release such personal information and data to any third parties save and except for the circumstances listed out under the section headed “Disclosure or Transfer of Data”.</p>
        <h3>Disclosure or Transfer of Data</h3>
        <p>Hjobs Hong Kong agrees to take all practicable steps to keep all personal information and data of Users confidential and/or undisclosed, subject to the following.</p>
        <p>Generally speaking, Hjobs Hong Kong will only disclose and/or transfer Users’ personal information and/or data to Hjobs Hong Kong’s personnel and staff for the purpose of providing services to Users and corporate clients of Hjobs Hong Kong who have made specific requests for such information and/or data with Users’ prior consent. However, Hjobs Hong Kong may disclose and/or transfer such information and/or data to third parties under the following circumstances:</p>
        <ul>
          <li>where the information and/or data is disclosed and/or transferred to any third party suppliers or external service providers who have been duly authorized by Hjobs Hong Kong to use such information and/or data and who will facilitate the services on the Site, under a duty of confidentiality;</li>
          <li>where the information and/or data is disclosed and/or transferred to any agents, affiliates or associates of Hjobs Hong Kong who have been duly authorized by Hjobs Hong Kong to use such information and/or data;</li>
          <li>where permitted under the “Terms and Conditions“including the “Talent Search Terms and Conditions” (see the Profiles Section below);</li>
          <li>where Hjobs Hong Kong needs to protect and defend its rights and property;</li>
          <li>where Hjobs Hong Kong considers necessary to do so in order to comply with the applicable laws and regulations, including without limitation compliance with a judicial proceeding, court order, or legal process served on the Site;</li>
          <li>where Hjobs Hong Kong deems necessary in order to deliver the products and services that we offer and cultivate a positive user experience; and</li>
          <li>where Hjobs Hong Kong deems necessary in order to maintain and improve the services on the Site.</li>
        </ul>
        <p>Personal data collected via the Site may be transferred, stored and processed in any country in which Hjobs Hong Kong or any member of the Hjobs Group operates. By using the Site, Users are deemed to have agreed to, consented to and authorized Hjobs Hong Kong to disclose and/or transfer their personal information and data under the circumstances stated above, as well as to any transfer of information (including the Information) outside of the Users’ country.</p>
        <h3>Hjobs Advertisers and Online Applications</h3>
        <ul>
          <li>Making an online application to a job advertisement on the Site is a free and optional service that requires users to complete mandatory fields (for example first name, last name, phone and email) so that Advertisers can identify and contact the applicants. When you apply for a job advertisement on the Site applications, including attachments and cover letters, are:</li>
          <li>forwarded directly on to the Advertiser and/or its nominated representative; and/or</li>
          <li>stored in the Hjobs data base on behalf of the Advertiser, who will be provided access to some/ all the data inputted by the advertiser.</li>
        </ul>
        <p>The Hjobs data base allows Advertisers to easily and effectively manage their recruitment process via one central facility made available by Hjobs.  By applying to a position advertised on the Site you are requesting that Hjobs pass the information you provide to the relevant Advertiser and/or their nominated representative. Any questions you have relating to a position advertised on Hjobs, your online application and/or the status of your application should be directed directly to the Advertiser or their nominated agent, not Hjobs.  Any Personal Information retained by Hjobs as part of your application will only be used in accord with this Privacy Statement. The use of your information (personal or otherwise) by Advertisers is not within the control of Hjobs and if you have any questions about how an Advertiser uses your personal information or want to request access to any personal information that you have sent as part of an application or that has been provided to them as part of a Hjobs Profile (as defined below), you have the right to contact that Advertiser directly.</p>
        <h3>Hjobs Profile</h3>
        <p>Hjobs provides all Registered Users with the option of creating a personal Hjobs Profile (“Hjobs Profile”). An Hjobs Profile can include a resume, employment and educational history, contact details, salary expectations, and preferred job classifications, other skills and locations. Advertisers who are approved by Hjobs are able to search the Hjobs’s Profile database to find and contact relevant candidates. Hjobs provides Registered Users with a number of privacy options in relation to the access granted by Hjobs to Advertisers in respect of their Hjobs Profiles and Registered Users can elect how much of their Hjobs profile they wish to share (if any) with Advertisers based on the following privacy settings:</p>
        <ul>
          <li><b>STANDARD</b> If you set your Hjobs Profile to standard, your Profile, except for your resume and contact details, can be seen by Advertisers searching Hjobs Profile database. Relevant content from the resume attached to your profile such as employment roles, descriptions of responsibilities and tasks, and educational history including schools, fields and periods of study, may also be scanned by Hjobs and presented to advertisers in the Profile database. Additionally, if an Advertiser wishes to purchase access to your Hjobs Profile, your full Hjobs Profile including your resume and contact details will be emailed immediately to the relevant Advertiser. Advertisers may also elect to send you a copy of the job opportunity for which they are recruiting, (by using the “invitations to apply for jobs” function).</li>
          <li><b>LIMITED</b> If you set your Hjobs Profile to limited, your Profile, except for your resume and contact details, can be seen by Advertisers searching Hjobs Profile database and Advertisers may elect to send you a copy of the job opportunity for which they are recruiting, (by using the “invitations to apply for jobs” function). However, due to your privacy setting, Advertisers cannot purchase access to your Hjobs profile.</li>
          <li><b>HIDDEN </b> If you set your Hjobs Profile to hidden, your Profile, is completely hidden (thereby preventing Advertisers from viewing your Hjobs Profile). Your Hjobs Profile will be stored in the ‘Profile’ area of the Site and you may alter the privacy settings at any time. Advertisers cannot purchase your profile or send you job opportunities.</li>
        </ul>
        <p>Advertisers who use the invitations to apply for jobs function will only receive access to your contact information if you respond directly to the job invitation sent to you.</p>
        <p>Where your profile has been bought by an Advertiser, you have replied to a job invitation sent by an Advertiser or you have applied for jobs directly on the Site using your profile, that Advertiser will have access to your up-to-date profile, including your contact details (as updated by you from time to time) for a period expiring two years from the date your profile was purchased, or date the Job Ad you responded was posted (as the case may be) (maximum of 24 months) (a “Participating Advertiser”). If however during the period that a Participating Advertiser has access to your updated profile, you subsequently change your profile setting to Hidden, whilst other Advertisers will no longer be able to see your profile, however, Participating Advertisers will retain the ability to access your profile (including your name), but will no longer be able to see your email address, contact phone number and work history.</p>
        <p>Additionally, to protect your privacy, all data stored by Hjobs on an advertiser’s behalf in the advertiser’s database (including data about you that the advertiser may have) will be deleted after a 2 year period.</p>
        <p>All information provided when creating a Hjobs Profile (including your name, resume, email address, telephone numbers, employment and educational history) may be used by Hjobs for the purpose of improving placement opportunities for you or for tailoring specific products to you.</p>
        <p>Where you create a Hjobs Profile on the Hjobs Hong Kong Site and select a privacy setting of Standard or Limited, you consent to your profile being viewed and/or accessed by Advertisers using the websites of any member of the Hjobs Group, which may result in the transfer of your personal data from Hong Kong to the other countries in which the other members of the Hjobs Group operate.</p>
        <p>Registered Users can modify their Hjobs Profile, their resume or modify the privacy options in relation to their Hjobs Profile at any time, by going to the Profile area of the Site.</p>
        <p>You may also elect to clear your Hjobs Profile altogether. Cleared Hjobs Profiles may still however be stored by Hjobs in testing or backup systems for a period of time. Hjobs reserves the right to disable or clear a Hjobs Profile at any time at its sole discretion.</p>
        <p>Advertisers that place job ads on Hjobs, and that purchase Hjobs Profiles are asked by Hjobs to comply with all relevant laws and obligations relating to the use and disclosure of personal information. The use of your information (personal or otherwise) by these Advertisers is not within the control of Hjobs and we cannot accept responsibility for the conduct of these companies.</p>
        <h3>Storing your resume</h3>
        <p>Registered Users may elect to store up to 2 resumes in their Hjobs account, and use those resumes when applying for a job.</p>
        <p>In order to provide an advertiser with the most relevant information about you (and depending on your Hjobs Profile privacy setting), the primary resume attached to your Hjobs Profile will also be scanned by Hjobs and relevant content may be displayed to advertisers in the Hjobs advertiser database. If you do not want content from your resume to be displayed to advertisers do not attach a resume or do not select “Standard” privacy. For more information on how your resume will be used, see above under the heading “Hjobs Profile”.</p>
        <h3>Subscription of Newsletter/Promotional Materials/Marketing Materials</h3>
        <p>Hjobs Hong Kong and its affiliates may from time to time send to members and Users of the Site newsletters, job openings and marketing materials based on the personal information and data that they have provided to Hjobs Hong Kong. Hjobs Hong Kong may use Users’ data in direct marketing and Hjobs Hong Kong requires the Users’ consent (which includes an indication of no objection) for that purpose. In this connection, please note that:</p>
        <ul>
          <li>the name, login ID and password, contact details, age, gender, date of birth, country of residence, nationality, education level, skill sets and work experience of Users held by Hjobs Hong Kong from time to time may be used by Hjobs Hong Kong and/or its authorized personnel or staff in direct marketing;</li>
          <li>the following classes of services, products and subjects may be marketed:
            <ul>
              <li>travelling related products and services;</li>
              <li>job-hunting and agencies services offered other than by Hjobs Hong Kong;</li>
              <li>various courses and programs for Users seeking jobs and career opportunities;</li>
              <li>special events hosted by Hjobs Hong Kong and its affiliates for members and Users, including but not limited to courses, workshops, and competitions;</li>
              <li>reward, loyalty or privilege programs and related products and services;</li>
              <li>special offers including coupons, discounts, group purchase offers and promotional campaigns;</li>
              <li>products and services offered by Hjobs Hong Kong’s affiliates and advertisers (the names of such affiliates and advertisers can be found in the application form(s) for the relevant products and services, as the case may be);</li>
              <li>donations and contributions for charitable and/or non-profit making purposes;<br /><br />
              However (except for where we assist charitable organisations) we will only market items which we believe are in the area of career related products and services.</li>
            </ul>
          </li>
          <li>the above products, services and subjects may be provided or (in the case of donations and contributions) solicited by Hjobs Hong Kong and/or;
            <ul>
              <li>Hjobs Hong Kong’s affiliates;</li>
              <li>third party service providers providing the products, services and subjects listed in paragraph (b) above; and</li>
              <li>charitable or non-profit making organizations;</li>
            </ul>
          </li>
          <li>in addition to marketing the above services, products, and subject itself, Hjobs Hong Kong also intends to provide the data described in paragraph (a) above to all or any of the persons described in paragraph (c) above for use by them in marketing those services, products and subjects, and Hjobs Hong Kong requires the Users’ written consent (which includes an indication of no objection) for that purpose; and</li>
          <li>Hjobs Hong Kong may receive money or other property in return for providing the data to the other persons in paragraph (d) above and, when requesting the Users’ written consent as described in paragraph (d) above, Hjobs Hong Kong will inform Users if Hjobs Hong Kong receives any money or other property in return for providing the data to other persons.</li>
        </ul>
        <p>In this regard, Users may choose to sign up or unsubscribe for such materials by logging into the registration or Users’ account maintenance webpage, or clicking on the automatic link appearing in each newsletter/message, or contact the Customer Support representative of Hjobs Hong Kong, whose contact details are set out under the section headed “Enquiries”.</p>
        <h3>Access to or request for correction of data</h3>
        <p>Any User is entitled to request access to or make amendments to his/her own personal information and data kept with Hjobs Hong Kong by contacting the Customer Support representative of Hjobs Hong Kong’s Customer Service Department at whose contact details are set out under the section headed “Enquiries”. Subject to the paragraph below, User may alternatively edit, amend or delete his/her personal information and data at any time by logging into the “My Hjobs Profile” section of the Site.</p>
        <p>In the event that a User wishes to access or amend his/her personal information and data, Hjobs Hong Kong may request him/her to provide personal details in order to verify and confirm his/her identity. Identity card number or passport number or business registration certificate number cannot be amended unless such data is proved to be inaccurate. Hjobs Hong Kong is required to respond to User’s requests within 40 days of his/her request and will endeavor to do so wherever possible, but Hjobs Hong Kong reserves the rights to charge the User a reasonable fee for doing so.</p>
        Cookies and Log Files
        <p>Hjobs Hong Kong does not collect any personally identifiable information from any Users whilst they visit and browse the Site. When Users access the Site, Hjobs Hong Kong records their visits only and does not collect their personal information or data. The Site’s server software will also record the domain name, server, address and track the pages Users visit and store such information in “cookies”, and gather and store information like internet protocol (IP) addresses, browser type, referring/exit pages, operating system, date/time stamp, and clickstream data in log files. All these are done without the Users being aware that they are occurring.</p>
        <p>Users can choose to accept or decline cookies. Most web browsers automatically accept cookies, but Users can modify their individual browser settings to decline cookies if they prefer. However, Users should note that disabling cookies on their browser may prevent them from taking full advantage of the Site.</p>
        <p>Hjobs Hong Kong does not link the information and data automatically collected in the above manner to any personally identifiable information. Hjobs Hong Kong generally uses such automatically collected information and data to estimate the audience size of the Site, gauge the popularity of various parts of the Site, track Users’ movements and number of entries in Hjobs Hong Kong’s promotional activities and special events, measure Users’ traffic patterns and administer the Site. Such automatically collected information and data will not be disclosed save and except in accordance with the section headed </p>“Disclosure or Transfer of Data”.
        <p>In addition, our third party advertising companies may place cookies on some of the pages Users visit on the Site. These cookies are designed to collect non-personally identifiable information in order to analyze Users’ interests and searches on our Site to help deliver more relevant advertisements when Users visit our Site and other websites. The non-personally identifiable information collected by these cookies may be shared with other third parties for purpose of managing and targeting advertisements and for market research analysis.</p>
        <h3>Links to Other Websites</h3>
        <p>The Site may provide links to other websites which are not owned or controlled by jobsDB, jobsDB Hong Kong or its affiliates. Personal information and data from Users may be collected on these other websites when Users visit such websites and make use of the services provided therein. Where and when Users decide to click on any advertisement or hyperlink on the Site which grants Users access to another website, the protection of Users’ personal information and data which are deemed to be private and confidential may be exposed in these other websites.</p>
        <p>Non-registered Users who gain access to the Site via their accounts in online social networking tools (including but not limited to Facebook, LinkedIn and Gmail) are deemed to have consented to the terms of this Privacy Statement, and such Users’ personal data which they have provided to those networking tools may be obtained by Hjobs Hong Kong and be used by jobsDB Hong Kong and its authorized persons in and outside of the User’s country for the purpose of providing services and marketing materials to the Users. Hjobs Hong Kong and its authorized personnel may gain access and use the personal data of such Users so obtained, subject to the other provisions of this Privacy Statement.</p>
        <p>This Privacy Statement is only applicable to the Site. Users are reminded that this Privacy Statement grants no protection to Users’ personal information and data that may be exposed on websites other than the Site, and Hjobs Hong Kong is not responsible for the privacy practices of such other websites. Users are strongly recommended to refer to the privacy policies of such other websites before using those websites.</p>
        <h3>Testimonials</h3>
        <p>Hjobs Hong Kong posts Users’ testimonials on the Site, which may contain personally identifiable information such as the Users’ names. Hjobs Hong Kong does obtain the Users’ consent prior to posting the testimonials to post their names along with their testimonials.</p>
        <h3>Security</h3>
        <p>The security of Users’ personal information and data is important to Hjobs Hong Kong. Hjobs Hong Kong will always strive to ensure that Users’ personal information and data will be protected against unauthorized access. Hjobs Hong Kong has implemented appropriate electronic and managerial measures in order to safeguard, protect and secure Users’ personal information and data.</p>
        <p>All personal information and data provided by Users are only accessible by the authorized personnel of Hjobs Hong Kong or its authorized third parties, and such personnel shall be instructed to observe the terms of this Privacy Statement when accessing such personal information and data. Users may rest assured that their personal information and data will only be kept for as long as is necessary to fulfill the purpose for which it is collected. Registered User should safeguard his/her unique Username and Password by keeping it secret and confidential and never share these details with anyone.</p>
        <p>Hjobs Hong Kong uses a third party service provider to facilitate the electronic payment transactions on the Site.</p>
        <p>Hjobs Hong Kong follows generally accepted industry standards to protect the personal information and data submitted by Users to the Site, both during transmission and once Hjobs Hong Kong receives it. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, while Hjobs Hong Kong strives to protect Users’ personal information and data against unauthorized access, Hjobs Hong Kong cannot guarantee its absolute security.</p>
        <h3>Retention of Personal Data</h3>
        <p>Once Hjobs Hong Kong has obtained a User’s personal information and/or data, it will be maintained securely in Hjobs Hong Kong’s system for the period necessary to fulfill the purposes for which the data was collected as set out under the section headed “Purpose of Collection of Personal Data”. Once registered, Users may terminate his/her membership of the Site by contacting the Customer Service representative of Hjobs Hong Kong’s Customer Service Department whose contact details are set out under the section headed “Enquiries“. Hjobs Hong Kong may retain User’s personal information even after User has closed his/her account if retention is reasonably necessary to comply with our legal obligations, meet regulatory requirements, resolve disputes between Users, prevent fraud and abuse, or enforce this Privacy Statement and the Terms and Conditions.</p>
        Changes in this Privacy Statement
        <p>Hjobs Hong Kong reserves the right to update, revise, modify or amend this Privacy Statement at any time as Hjobs Hong Kong deems necessary, so Users are strongly recommended to review this Privacy Statement frequently. If Hjobs Hong Kong decides to update, revise, modify or amend this Privacy Statement, Hjobs Hong Kong will post those changes to this webpage and/or other places Hjobs Hong Kong deems appropriate so that Users would be aware of what information Hjobs Hong Kong collects, how Hjobs Hong Kong uses it, and under what circumstances, if any, Hjobs Hong Kong discloses it.</p>
        <p>If Hjobs Hong Kong makes material changes to this Privacy Statement, Hjobs Hong Kong will notify Users on this webpage, by email, or by means of a notice on the home page of Hjobs Hong Kong. Such changes to this Privacy Statement shall apply from the time that Hjobs Hong Kong posts the same on this webpage. Users’ continued use of the Site and services on the Site shall constitute acceptance of the changes to this Privacy Statement.</p>
        <h3>Enquiries</h3>
        <p>Should you have any enquiries relating to this Privacy Statement, please email at info@hjobs.hk.</p>
      </section>
    );
  }
}

export default Terms;
